package repository;

import generator.entity.Transfer;
import generator.entity.TransferExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TransferMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer
     *
     * @mbggenerated
     */
    int countByExample(TransferExample example);


    Transfer lockByBizNo(String bizNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer
     *
     * @mbggenerated
     */
    int deleteByExample(TransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String bizNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer
     *
     * @mbggenerated
     */
    int insert(Transfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer
     *
     * @mbggenerated
     */
    int insertSelective(Transfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer
     *
     * @mbggenerated
     */
    List<Transfer> selectByExample(TransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer
     *
     * @mbggenerated
     */
    Transfer selectByPrimaryKey(String bizNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Transfer record, @Param("example") TransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Transfer record, @Param("example") TransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Transfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Transfer record);
}