package generator.entity;

import com.yjf.common.util.ToString;

import java.util.Date;

public class Transfer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.biz_no
     *
     * @mbggenerated
     */
    private String bizNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.account_no
     *
     * @mbggenerated
     */
    private String accountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.amount
     *
     * @mbggenerated
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.bank_account_name
     *
     * @mbggenerated
     */
    private String bankAccountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.bank_account_no
     *
     * @mbggenerated
     */
    private String bankAccountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.sec_index
     *
     * @mbggenerated
     */
    private String secIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.bank_code
     *
     * @mbggenerated
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.bank_name
     *
     * @mbggenerated
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.card_no
     *
     * @mbggenerated
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.charge_amount
     *
     * @mbggenerated
     */
    private Long chargeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.charge_no
     *
     * @mbggenerated
     */
    private String chargeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.currency
     *
     * @mbggenerated
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.delay_hours
     *
     * @mbggenerated
     */
    private Integer delayHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.fail_reason
     *
     * @mbggenerated
     */
    private String failReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.joint_account_no
     *
     * @mbggenerated
     */
    private String jointAccountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.joint_use_for
     *
     * @mbggenerated
     */
    private String jointUseFor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.seller_card_no
     *
     * @mbggenerated
     */
    private String sellerCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.seller_user_id
     *
     * @mbggenerated
     */
    private String sellerUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.selller_account_no
     *
     * @mbggenerated
     */
    private String selllerAccountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.transfer_no
     *
     * @mbggenerated
     */
    private String transferNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.joint_out_type
     *
     * @mbggenerated
     */
    private String jointOutType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.control_type
     *
     * @mbggenerated
     */
    private String controlType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.raw_update_time
     *
     * @mbggenerated
     */
    private Date rawUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.raw_add_time
     *
     * @mbggenerated
     */
    private Date rawAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.gid
     *
     * @mbggenerated
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.inlet
     *
     * @mbggenerated
     */
    private String inlet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.merchant_acc_no
     *
     * @mbggenerated
     */
    private String merchantAccNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.merchant_card_no
     *
     * @mbggenerated
     */
    private String merchantCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.merchant_order_no
     *
     * @mbggenerated
     */
    private String merchantOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.merch_order_no
     *
     * @mbggenerated
     */
    private String merchOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.merchant_user_id
     *
     * @mbggenerated
     */
    private String merchantUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.product_code
     *
     * @mbggenerated
     */
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.product_status
     *
     * @mbggenerated
     */
    private String productStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.orgi_delay_hours
     *
     * @mbggenerated
     */
    private Integer orgiDelayHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.delay_hours_change_memo
     *
     * @mbggenerated
     */
    private String delayHoursChangeMemo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.biz_no
     *
     * @return the value of transfer.biz_no
     *
     * @mbggenerated
     */
    public String getBizNo() {
        return bizNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.biz_no
     *
     * @param bizNo the value for transfer.biz_no
     *
     * @mbggenerated
     */
    public void setBizNo(String bizNo) {
        this.bizNo = bizNo == null ? null : bizNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.account_no
     *
     * @return the value of transfer.account_no
     *
     * @mbggenerated
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.account_no
     *
     * @param accountNo the value for transfer.account_no
     *
     * @mbggenerated
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo == null ? null : accountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.amount
     *
     * @return the value of transfer.amount
     *
     * @mbggenerated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.amount
     *
     * @param amount the value for transfer.amount
     *
     * @mbggenerated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.bank_account_name
     *
     * @return the value of transfer.bank_account_name
     *
     * @mbggenerated
     */
    public String getBankAccountName() {
        return bankAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.bank_account_name
     *
     * @param bankAccountName the value for transfer.bank_account_name
     *
     * @mbggenerated
     */
    public void setBankAccountName(String bankAccountName) {
        this.bankAccountName = bankAccountName == null ? null : bankAccountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.bank_account_no
     *
     * @return the value of transfer.bank_account_no
     *
     * @mbggenerated
     */
    public String getBankAccountNo() {
        return bankAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.bank_account_no
     *
     * @param bankAccountNo the value for transfer.bank_account_no
     *
     * @mbggenerated
     */
    public void setBankAccountNo(String bankAccountNo) {
        this.bankAccountNo = bankAccountNo == null ? null : bankAccountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.sec_index
     *
     * @return the value of transfer.sec_index
     *
     * @mbggenerated
     */
    public String getSecIndex() {
        return secIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.sec_index
     *
     * @param secIndex the value for transfer.sec_index
     *
     * @mbggenerated
     */
    public void setSecIndex(String secIndex) {
        this.secIndex = secIndex == null ? null : secIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.bank_code
     *
     * @return the value of transfer.bank_code
     *
     * @mbggenerated
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.bank_code
     *
     * @param bankCode the value for transfer.bank_code
     *
     * @mbggenerated
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.bank_name
     *
     * @return the value of transfer.bank_name
     *
     * @mbggenerated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.bank_name
     *
     * @param bankName the value for transfer.bank_name
     *
     * @mbggenerated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.card_no
     *
     * @return the value of transfer.card_no
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.card_no
     *
     * @param cardNo the value for transfer.card_no
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.charge_amount
     *
     * @return the value of transfer.charge_amount
     *
     * @mbggenerated
     */
    public Long getChargeAmount() {
        return chargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.charge_amount
     *
     * @param chargeAmount the value for transfer.charge_amount
     *
     * @mbggenerated
     */
    public void setChargeAmount(Long chargeAmount) {
        this.chargeAmount = chargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.charge_no
     *
     * @return the value of transfer.charge_no
     *
     * @mbggenerated
     */
    public String getChargeNo() {
        return chargeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.charge_no
     *
     * @param chargeNo the value for transfer.charge_no
     *
     * @mbggenerated
     */
    public void setChargeNo(String chargeNo) {
        this.chargeNo = chargeNo == null ? null : chargeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.currency
     *
     * @return the value of transfer.currency
     *
     * @mbggenerated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.currency
     *
     * @param currency the value for transfer.currency
     *
     * @mbggenerated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.delay_hours
     *
     * @return the value of transfer.delay_hours
     *
     * @mbggenerated
     */
    public Integer getDelayHours() {
        return delayHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.delay_hours
     *
     * @param delayHours the value for transfer.delay_hours
     *
     * @mbggenerated
     */
    public void setDelayHours(Integer delayHours) {
        this.delayHours = delayHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.fail_reason
     *
     * @return the value of transfer.fail_reason
     *
     * @mbggenerated
     */
    public String getFailReason() {
        return failReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.fail_reason
     *
     * @param failReason the value for transfer.fail_reason
     *
     * @mbggenerated
     */
    public void setFailReason(String failReason) {
        this.failReason = failReason == null ? null : failReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.joint_account_no
     *
     * @return the value of transfer.joint_account_no
     *
     * @mbggenerated
     */
    public String getJointAccountNo() {
        return jointAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.joint_account_no
     *
     * @param jointAccountNo the value for transfer.joint_account_no
     *
     * @mbggenerated
     */
    public void setJointAccountNo(String jointAccountNo) {
        this.jointAccountNo = jointAccountNo == null ? null : jointAccountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.joint_use_for
     *
     * @return the value of transfer.joint_use_for
     *
     * @mbggenerated
     */
    public String getJointUseFor() {
        return jointUseFor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.joint_use_for
     *
     * @param jointUseFor the value for transfer.joint_use_for
     *
     * @mbggenerated
     */
    public void setJointUseFor(String jointUseFor) {
        this.jointUseFor = jointUseFor == null ? null : jointUseFor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.seller_card_no
     *
     * @return the value of transfer.seller_card_no
     *
     * @mbggenerated
     */
    public String getSellerCardNo() {
        return sellerCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.seller_card_no
     *
     * @param sellerCardNo the value for transfer.seller_card_no
     *
     * @mbggenerated
     */
    public void setSellerCardNo(String sellerCardNo) {
        this.sellerCardNo = sellerCardNo == null ? null : sellerCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.seller_user_id
     *
     * @return the value of transfer.seller_user_id
     *
     * @mbggenerated
     */
    public String getSellerUserId() {
        return sellerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.seller_user_id
     *
     * @param sellerUserId the value for transfer.seller_user_id
     *
     * @mbggenerated
     */
    public void setSellerUserId(String sellerUserId) {
        this.sellerUserId = sellerUserId == null ? null : sellerUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.selller_account_no
     *
     * @return the value of transfer.selller_account_no
     *
     * @mbggenerated
     */
    public String getSelllerAccountNo() {
        return selllerAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.selller_account_no
     *
     * @param selllerAccountNo the value for transfer.selller_account_no
     *
     * @mbggenerated
     */
    public void setSelllerAccountNo(String selllerAccountNo) {
        this.selllerAccountNo = selllerAccountNo == null ? null : selllerAccountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.transfer_no
     *
     * @return the value of transfer.transfer_no
     *
     * @mbggenerated
     */
    public String getTransferNo() {
        return transferNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.transfer_no
     *
     * @param transferNo the value for transfer.transfer_no
     *
     * @mbggenerated
     */
    public void setTransferNo(String transferNo) {
        this.transferNo = transferNo == null ? null : transferNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.joint_out_type
     *
     * @return the value of transfer.joint_out_type
     *
     * @mbggenerated
     */
    public String getJointOutType() {
        return jointOutType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.joint_out_type
     *
     * @param jointOutType the value for transfer.joint_out_type
     *
     * @mbggenerated
     */
    public void setJointOutType(String jointOutType) {
        this.jointOutType = jointOutType == null ? null : jointOutType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.user_id
     *
     * @return the value of transfer.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.user_id
     *
     * @param userId the value for transfer.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.control_type
     *
     * @return the value of transfer.control_type
     *
     * @mbggenerated
     */
    public String getControlType() {
        return controlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.control_type
     *
     * @param controlType the value for transfer.control_type
     *
     * @mbggenerated
     */
    public void setControlType(String controlType) {
        this.controlType = controlType == null ? null : controlType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.raw_update_time
     *
     * @return the value of transfer.raw_update_time
     *
     * @mbggenerated
     */
    public Date getRawUpdateTime() {
        return rawUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.raw_update_time
     *
     * @param rawUpdateTime the value for transfer.raw_update_time
     *
     * @mbggenerated
     */
    public void setRawUpdateTime(Date rawUpdateTime) {
        this.rawUpdateTime = rawUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.raw_add_time
     *
     * @return the value of transfer.raw_add_time
     *
     * @mbggenerated
     */
    public Date getRawAddTime() {
        return rawAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.raw_add_time
     *
     * @param rawAddTime the value for transfer.raw_add_time
     *
     * @mbggenerated
     */
    public void setRawAddTime(Date rawAddTime) {
        this.rawAddTime = rawAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.gid
     *
     * @return the value of transfer.gid
     *
     * @mbggenerated
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.gid
     *
     * @param gid the value for transfer.gid
     *
     * @mbggenerated
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.inlet
     *
     * @return the value of transfer.inlet
     *
     * @mbggenerated
     */
    public String getInlet() {
        return inlet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.inlet
     *
     * @param inlet the value for transfer.inlet
     *
     * @mbggenerated
     */
    public void setInlet(String inlet) {
        this.inlet = inlet == null ? null : inlet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.memo
     *
     * @return the value of transfer.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.memo
     *
     * @param memo the value for transfer.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.merchant_acc_no
     *
     * @return the value of transfer.merchant_acc_no
     *
     * @mbggenerated
     */
    public String getMerchantAccNo() {
        return merchantAccNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.merchant_acc_no
     *
     * @param merchantAccNo the value for transfer.merchant_acc_no
     *
     * @mbggenerated
     */
    public void setMerchantAccNo(String merchantAccNo) {
        this.merchantAccNo = merchantAccNo == null ? null : merchantAccNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.merchant_card_no
     *
     * @return the value of transfer.merchant_card_no
     *
     * @mbggenerated
     */
    public String getMerchantCardNo() {
        return merchantCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.merchant_card_no
     *
     * @param merchantCardNo the value for transfer.merchant_card_no
     *
     * @mbggenerated
     */
    public void setMerchantCardNo(String merchantCardNo) {
        this.merchantCardNo = merchantCardNo == null ? null : merchantCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.merchant_order_no
     *
     * @return the value of transfer.merchant_order_no
     *
     * @mbggenerated
     */
    public String getMerchantOrderNo() {
        return merchantOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.merchant_order_no
     *
     * @param merchantOrderNo the value for transfer.merchant_order_no
     *
     * @mbggenerated
     */
    public void setMerchantOrderNo(String merchantOrderNo) {
        this.merchantOrderNo = merchantOrderNo == null ? null : merchantOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.merch_order_no
     *
     * @return the value of transfer.merch_order_no
     *
     * @mbggenerated
     */
    public String getMerchOrderNo() {
        return merchOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.merch_order_no
     *
     * @param merchOrderNo the value for transfer.merch_order_no
     *
     * @mbggenerated
     */
    public void setMerchOrderNo(String merchOrderNo) {
        this.merchOrderNo = merchOrderNo == null ? null : merchOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.merchant_user_id
     *
     * @return the value of transfer.merchant_user_id
     *
     * @mbggenerated
     */
    public String getMerchantUserId() {
        return merchantUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.merchant_user_id
     *
     * @param merchantUserId the value for transfer.merchant_user_id
     *
     * @mbggenerated
     */
    public void setMerchantUserId(String merchantUserId) {
        this.merchantUserId = merchantUserId == null ? null : merchantUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.product_code
     *
     * @return the value of transfer.product_code
     *
     * @mbggenerated
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.product_code
     *
     * @param productCode the value for transfer.product_code
     *
     * @mbggenerated
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.product_status
     *
     * @return the value of transfer.product_status
     *
     * @mbggenerated
     */
    public String getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.product_status
     *
     * @param productStatus the value for transfer.product_status
     *
     * @mbggenerated
     */
    public void setProductStatus(String productStatus) {
        this.productStatus = productStatus == null ? null : productStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.orgi_delay_hours
     *
     * @return the value of transfer.orgi_delay_hours
     *
     * @mbggenerated
     */
    public Integer getOrgiDelayHours() {
        return orgiDelayHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.orgi_delay_hours
     *
     * @param orgiDelayHours the value for transfer.orgi_delay_hours
     *
     * @mbggenerated
     */
    public void setOrgiDelayHours(Integer orgiDelayHours) {
        this.orgiDelayHours = orgiDelayHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.delay_hours_change_memo
     *
     * @return the value of transfer.delay_hours_change_memo
     *
     * @mbggenerated
     */
    public String getDelayHoursChangeMemo() {
        return delayHoursChangeMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.delay_hours_change_memo
     *
     * @param delayHoursChangeMemo the value for transfer.delay_hours_change_memo
     *
     * @mbggenerated
     */
    public void setDelayHoursChangeMemo(String delayHoursChangeMemo) {
        this.delayHoursChangeMemo = delayHoursChangeMemo == null ? null : delayHoursChangeMemo.trim();
    }

    @Override
    public String toString() {
        return ToString.toString(this);
    }
}